---
title: "Step function sim"
output: html_notebook
---

Glen Nov 2025


Simulate a step function lab test for menopause and show that YoGlen is insensitive to FMP shifting and scaling (i.e. noise)


```{r}
gRootName = "yoglen"
gSaveDefault=F

outputDir = "/home/glen/yoglen" #set analysis directory here

source(sprintf("%s/menopause_script.R",outputDir),verbose=0)
library(ggplot2)
```

load in menopause distribution
```{r}
set.seed(123)
#NHANES FMP looks like normal at 50, 4 plus early abnormals
mu0 = 50
sigma0 = 4 

smeno0 = Surv(rnorm(1e5,mu0,sigma0))
```

now simulate some data
#simplest possible sim - no noise, 1 variable going from 0 to 1
```{r}
N    = 1e5
age  = runif(N,50-20,50+20)
age_menopause = rnorm(N,mu0,sigma0)
ysd = .1

data = data.frame(id=1:N,age=age,age_menopause=age_menopause,t=age-age_menopause)
data[,'menopause'] = 1*(data[,"t"] > 0)
data[,'y'] = 1*(data[,"t"] > 0)+rnorm(nrow(data),0,ysd)

#max difference between populations means is ~4 years
  #Schoenaker, D. A. J. M., Jackson, C. A., Rowlands, J. V. & Mishra, G. D. Socioeconomic position, lifestyle factors and age at natural menopause: a systematic review and meta-analyses of studies across six continents. Int. J. Epidemiol. 43, 1542–1562 (2014).
bias=4
data[,"biased_age_menopause"] = data[,"age_menopause"] + bias

#1 year is typical noise; we see pileup every 5 years, so say 2.5 years
  #den Tonkelaar, I. Validity and reproducibility of self-reported age at menopause in women participating in the DOM-project. Maturitas 27, 117–123 (1997).
#can't see a difference so crank it up
dsigma = 4
data[,"noisy_age_menopause"] = data[,"age_menopause"] + rnorm(nrow(data),0,dsigma)
```

histograms
```{r}
plotdf = list()
plotdf[[1]] = data.frame(age_menopause=data[,"age_menopause"],group="gt")
plotdf[[2]] = data.frame(age_menopause=data[,"biased_age_menopause"],group="biased")
plotdf[[3]] = data.frame(age_menopause=data[,"noisy_age_menopause"],group="noisy")
plotdf=do.call(rbind,plotdf)
exactdf = list()
exactdf[[1]] = data.frame(age_menopause=seq(30,70,by=.1),group="gt")
exactdf[[2]] = data.frame(age_menopause=seq(30,70,by=.1),group="biased")
exactdf[[3]] = data.frame(age_menopause=seq(30,70,by=.1),group="noisy")
exactdf[[1]][,"p"] = dnorm(exactdf[[1]][,"age_menopause"],mu0,sigma0)
exactdf[[2]][,"p"] = dnorm(exactdf[[2]][,"age_menopause"],mu0+bias,sigma0)
exactdf[[3]][,"p"] = dnorm(exactdf[[3]][,"age_menopause"],mu0,sqrt(sigma0^2+dsigma^2))
exactdf=do.call(rbind,exactdf)


cols=RColorBrewer::brewer.pal(n = 2, name = "Dark2")  
cols = c(gt="black",biased=cols[1],noisy=cols[2])
g = ggplot(plotdf,aes(x=age_menopause,colour=group,fill=group))+
  geom_histogram(aes(y = after_stat(density)),position = "identity",alpha = 0.35, linewidth = 0.3)+
  geom_line(data=exactdf,aes(y=p),size=1)+
  scale_color_manual(values=cols)+
  scale_fill_manual(values=cols)+
  labs(x="Age of menopause",y="Density",title="a)")+
  scale_y_continuous(breaks=seq(0,.1,by=.02))+
  #scale_y_continuous(breaks=seq(0,.1,by=.02),labels=sprintf("%.0f%%",100*seq(0,.1,by=.02)))+
  theme_classic(base_size=20)
g

save=gSaveDefault
if(save)
{
  ggsave(sprintf("%s/results/yoglen_validation_step_function_age_of_menopause.pdf",outputDir),g,width=12,height=7)
}
```

exact fit
```{r}
am = data[,"age_menopause"]
am[data[,"menopause"]==0] = NA #hide all pre-menopause ages
meno = data[,"menopause"]
t=am
t[data[,"menopause"]==0] = data[data[,"menopause"]==0,"age"]  
smeno=Surv(t,data[,"menopause"])

mdata = data.frame(RIDAGEYR=data[,"age"],menopause=meno,y=data[,"y"],age_menopause=am,y=data[,"y"])
fit0_v1 = FitLatentFun(data=mdata,vars=NULL,ref_age=rep(NA,nrow(smeno)),ref_status=smeno[,2],ref_age_menopause=smeno[,1],iterativeSurvFit=F,nboot=1,
                  FitFun = WeightedPiecewiseLM,VarInFit=F,f=y~t)

#hide it all: #looks great
meno = NA*meno
am   = NA*am
mdata = data.frame(RIDAGEYR=data[,"age"],menopause=meno,y=data[,"y"],age_menopause=am,y=data[,"y"])
fit0_v2 = FitLatentFun(data=mdata,vars="y",ref_age=rep(NA,nrow(smeno)),ref_status=smeno[,2],ref_age_menopause=smeno[,1],iterativeSurvFit=F,nboot=1,
                  FitFun = WeightedPiecewiseLM,VarInFit=F,f=y~t)

```

biased fit
```{r}
am = data[,"biased_age_menopause"]
am[data[,"menopause"]==0] = NA #hide all pre-menopause ages
meno = data[,"menopause"]
t=am
t[data[,"menopause"]==0] = data[data[,"menopause"]==0,"age"]  
smeno=Surv(t,data[,"menopause"])

mdata = data.frame(RIDAGEYR=data[,"age"],menopause=meno,y=data[,"y"],age_menopause=am,y=data[,"y"])
fitb_v1 = FitLatentFun(data=mdata,vars=NULL,ref_age=rep(NA,nrow(smeno)),ref_status=smeno[,2],ref_age_menopause=smeno[,1],iterativeSurvFit=F,nboot=1,
                  FitFun = WeightedPiecewiseLM,VarInFit=F,f=y~t)

#hide it all: #looks great
meno = NA*meno
am   = NA*am
mdata = data.frame(RIDAGEYR=data[,"age"],menopause=meno,y=data[,"y"],age_menopause=am,y=data[,"y"])
fitb_v2 = FitLatentFun(data=mdata,vars="y",ref_age=rep(NA,nrow(smeno)),ref_status=smeno[,2],ref_age_menopause=smeno[,1],iterativeSurvFit=F,nboot=1,
                  FitFun = WeightedPiecewiseLM,VarInFit=F,f=y~t)

```

noisy fit
```{r}
am = data[,"noisy_age_menopause"]
am[data[,"menopause"]==0] = NA #hide all pre-menopause ages
meno = data[,"menopause"]
t=am
t[data[,"menopause"]==0] = data[data[,"menopause"]==0,"age"]  
smeno=Surv(t,data[,"menopause"])

mdata = data.frame(RIDAGEYR=data[,"age"],menopause=meno,y=data[,"y"],age_menopause=am,y=data[,"y"])
fitn_v1 = FitLatentFun(data=mdata,vars=NULL,ref_age=rep(NA,nrow(smeno)),ref_status=smeno[,2],ref_age_menopause=smeno[,1],iterativeSurvFit=F,nboot=1,
                  FitFun = WeightedPiecewiseLM,VarInFit=F,f=y~t)

#hide it all: #looks great
meno = NA*meno
am   = NA*am
mdata = data.frame(RIDAGEYR=data[,"age"],menopause=meno,y=data[,"y"],age_menopause=am,y=data[,"y"])
fitn_v2 = FitLatentFun(data=mdata,vars="y",ref_age=rep(NA,nrow(smeno)),ref_status=smeno[,2],ref_age_menopause=smeno[,1],iterativeSurvFit=F,nboot=1,
                  FitFun = WeightedPiecewiseLM,VarInFit=F,f=y~t)

```
estimated ditsributions:
```{r}
hist(data[,"age_menopause"],freq=F)
hist(data[,"biased_age_menopause"],freq=F,col=scales::alpha(2,.5),add=T)
hist(data[,"noisy_age_menopause"],freq=F,col=scales::alpha(3,.5),add=T,breaks=20)
curve(dnorm(x,mu0,sqrt(sigma0^2+dsigma^2)),add=T,col=3)
legend("topleft",c("GT","biased","noisy"),col=1:3,lty=1:3)


plot(fit0_v1$control$menopause_ages,apply(fit0_v1$pzy,2,mean))
lines(fitb_v1$control$menopause_ages,apply(fitb_v1$pzy,2,mean),col=2,lty=1)
lines(fitn_v1$control$menopause_ages,apply(fitn_v1$pzy,2,mean),col=3,lty=2)

plot(fit0_v2$control$menopause_ages,apply(fit0_v2$pzy,2,mean))
lines(fitb_v2$control$menopause_ages,apply(fitb_v2$pzy,2,mean),col=2,lty=1)
lines(fitn_v2$control$menopause_ages,apply(fitn_v2$pzy,2,mean),col=3,lty=2)
```

```{r}
#now impute & aggregate
tcuts = seq(-25,25,by=.25)
mi    = list()

M = 15
for (j in 1:M)
{
  mi[[j]] = mdata
}

save=gSaveDefault
load=T
file=sprintf("%s/results/yoglen_step_function_test_mi.rds",outputDir)
if(file.exists(file) & load)
{
  mi=readRDS(file)
} else
{
  for (i in 1:nrow(mdata)) 
  {
    #cat(".")
    #t2 = SmoothAndSample(M,pz=fitn_v1$pzy[i,],agez = fitn_v1$control$menopause_ages)
    t = sample(fit0_v1$control$menopause_ages,size=M,replace=T,prob=fit0_v1$pzy[i,])
    for (j in 1:M) mi[[j]][i,"age_menopause_imp"] = t[j]
    rm(t)
    t = sample(fitb_v1$control$menopause_ages,size=M,replace=T,prob=fitb_v1$pzy[i,])
    for (j in 1:M) mi[[j]][i,"age_menopause_bias_imp"] = t[j]
    rm(t)
    t = sample(fitn_v1$control$menopause_ages,size=M,replace=T,prob=fitn_v1$pzy[i,])
    for (j in 1:M) mi[[j]][i,"age_menopause_noise_imp"] = t[j]
    rm(t)
  
    t = sample(fit0_v2$control$menopause_ages,size=M,replace=T,prob=fit0_v2$pzy[i,])
    for (j in 1:M) mi[[j]][i,"age_menopause_imp2"] = t[j]
    rm(t)
    t = sample(fitb_v2$control$menopause_ages,size=M,replace=T,prob=fitb_v2$pzy[i,])
    for (j in 1:M) mi[[j]][i,"age_menopause_bias_imp2"] = t[j]
    rm(t)
    t = sample(fitn_v2$control$menopause_ages,size=M,replace=T,prob=fitn_v2$pzy[i,])
    for (j in 1:M) mi[[j]][i,"age_menopause_noise_imp2"] = t[j]
    rm(t)
  }
  if(save) saveRDS(mi,file)
}

```

```{r}
agg0   = list()
agg0se = list()
aggb_v1   = list()
aggb_v1se = list()
aggn_v1   = list()
aggn_v1se = list()
aggb_v2   = list()
aggb_v2se = list()
aggn_v2   = list()
aggn_v2se = list()
for (j in 1:M)
{
  mi[[j]][,"t"]    = mi[[j]][,"RIDAGEYR"] - mi[[j]][,"age_menopause_imp"]
  mi[[j]][,"tcut"] = cut(mi[[j]][,"t"],tcuts,include.lowest=T)
  agg0[[j]]   = as.matrix(aggregate(mi[[j]][,c("t","y")],by=mi[[j]][,"tcut",drop=F],mean,na.rm=T,drop=F)[,c("t","y")])
  agg0se[[j]] = as.matrix(aggregate(mi[[j]][,c("t","y")],by=mi[[j]][,"tcut",drop=F],SEM,na.rm=T,drop=F)[,c("t","y")])

  mi[[j]][,"t"]    = mi[[j]][,"RIDAGEYR"] - mi[[j]][,"age_menopause_bias_imp"]
  mi[[j]][,"tcut"] = cut(mi[[j]][,"t"],tcuts,include.lowest=T)
  aggb_v1[[j]]   = as.matrix(aggregate(mi[[j]][,c("t","y")],by=mi[[j]][,"tcut",drop=F],mean,na.rm=T,drop=F)[,c("t","y")])
  aggb_v1se[[j]] = as.matrix(aggregate(mi[[j]][,c("t","y")],by=mi[[j]][,"tcut",drop=F],SEM,na.rm=T,drop=F)[,c("t","y")])
  
  mi[[j]][,"t"]    = mi[[j]][,"RIDAGEYR"] - mi[[j]][,"age_menopause_noise_imp"]
  mi[[j]][,"tcut"] = cut(mi[[j]][,"t"],tcuts,include.lowest=T)
  aggn_v1[[j]]   = as.matrix(aggregate(mi[[j]][,c("t","y")],by=mi[[j]][,"tcut",drop=F],mean,na.rm=T,drop=F)[,c("t","y")])
  aggn_v1se[[j]] = as.matrix(aggregate(mi[[j]][,c("t","y")],by=mi[[j]][,"tcut",drop=F],SEM,na.rm=T,drop=F)[,c("t","y")])
  
  mi[[j]][,"t"]    = mi[[j]][,"RIDAGEYR"] - mi[[j]][,"age_menopause_bias_imp2"]
  mi[[j]][,"tcut"] = cut(mi[[j]][,"t"],tcuts,include.lowest=T)
  aggb_v2[[j]]   = as.matrix(aggregate(mi[[j]][,c("t","y")],by=mi[[j]][,"tcut",drop=F],mean,na.rm=T,drop=F)[,c("t","y")])
  aggb_v2se[[j]] = as.matrix(aggregate(mi[[j]][,c("t","y")],by=mi[[j]][,"tcut",drop=F],SEM,na.rm=T,drop=F)[,c("t","y")])
  
  mi[[j]][,"t"]    = mi[[j]][,"RIDAGEYR"] - mi[[j]][,"age_menopause_noise_imp2"]
  mi[[j]][,"tcut"] = cut(mi[[j]][,"t"],tcuts,include.lowest=T)
  aggn_v2[[j]]   = as.matrix(aggregate(mi[[j]][,c("t","y")],by=mi[[j]][,"tcut",drop=F],mean,na.rm=T,drop=F)[,c("t","y")])
  aggn_v2se[[j]] = as.matrix(aggregate(mi[[j]][,c("t","y")],by=mi[[j]][,"tcut",drop=F],SEM,na.rm=T,drop=F)[,c("t","y")])
}
r = RubinMat(agg0,lse = agg0se,na.rm=T)
agg0 = as.data.frame(r[[1]])
agg0[,sprintf("%sse",colnames(r[[2]]))] = r[[2]]
r = RubinMat(aggb_v1,lse = aggb_v1se,na.rm=T)
aggb_v1 = as.data.frame(r[[1]])
aggb_v1[,sprintf("%sse",colnames(r[[2]]))] = r[[2]]
r = RubinMat(aggn_v1,lse = aggn_v1se,na.rm=T)
aggn_v1 = as.data.frame(r[[1]])
aggn_v1[,sprintf("%sse",colnames(r[[2]]))] = r[[2]]
r = RubinMat(aggb_v2,lse = aggb_v2se,na.rm=T)
aggb_v2 = as.data.frame(r[[1]])
aggb_v2[,sprintf("%sse",colnames(r[[2]]))] = r[[2]]
r = RubinMat(aggn_v2,lse = aggn_v2se,na.rm=T)
aggn_v2 = as.data.frame(r[[1]])
aggn_v2[,sprintf("%sse",colnames(r[[2]]))] = r[[2]]

```
```{r}
load=T
save=gSaveDefault
models = list(splineJump = GAMSplineJump,spline = GAMSpline) 
mc.cores=1

for (j in 1:length(mi))
{
  mi[[j]][,"var"]    = mi[[j]][,"y"]
  mi[[j]][,"menopause"] = data[,"menopause"]
    
  mi[[j]][,"ti"]    = mi[[j]][,"RIDAGEYR"] - mi[[j]][,"age_menopause_imp"]
  mi[[j]][,"tb1"]    = mi[[j]][,"RIDAGEYR"] - mi[[j]][,"age_menopause_bias_imp"]
  mi[[j]][,"tn1"]    = mi[[j]][,"RIDAGEYR"] - mi[[j]][,"age_menopause_noise_imp"]
  mi[[j]][,"tb2"]    = mi[[j]][,"RIDAGEYR"] - mi[[j]][,"age_menopause_bias_imp2"]
  mi[[j]][,"tn2"]    = mi[[j]][,"RIDAGEYR"] - mi[[j]][,"age_menopause_noise_imp2"]
}



file=sprintf("%s/results/yoglen0_step_function.rds",outputDir)
if(file.exists(file) & load)
{
  ms0=readRDS(file)
} else
{
  ms0 = ModelSelectionMI(mi,vars="var",xcol="ti",models=models,Nfolds=5,Nrepeats=5,xdelta=c(.01,1,2,3,4,5,10),refModels = 1:length(models),mc.cores=mc.cores)
  if(save) 
  {
    saveRDS(ms0,file)
  }
}

file=sprintf("%s/results/yoglen_bias_v1_step_function.rds",outputDir)
if(file.exists(file) & load)
{
  msb_v1=readRDS(file)
} else
{
  msb_v1 = ModelSelectionMI(mi,vars="var",xcol="tb1",models=models,Nfolds=5,Nrepeats=5,xdelta=c(.01,1,2,3,4,5,10),refModels = 1:length(models),mc.cores=mc.cores)
  if(save) 
  {
    saveRDS(msb_v1,file)
  }
}

file=sprintf("%s/results/yoglen_noise_v1_step_function.rds",outputDir)
if(file.exists(file) & load)
{
  msn_v1=readRDS(file)
} else
{
  msn_v1 = ModelSelectionMI(mi,vars="var",xcol="tn1",models=models,Nfolds=5,Nrepeats=5,xdelta=c(.01,1,2,3,4,5,10),refModels = 1:length(models),mc.cores=mc.cores)
  if(save) 
  {
    saveRDS(msn_v1,file)
  }
}

file=sprintf("%s/results/yoglen_bias_v2_step_function.rds",outputDir)
if(file.exists(file) & load)
{
  msb_v2=readRDS(file)
} else
{
  msb_v2 = ModelSelectionMI(mi,vars="var",xcol="tb2",models=models,Nfolds=5,Nrepeats=5,xdelta=c(.01,1,2,3,4,5,10),refModels = 1:length(models),mc.cores=mc.cores)
  if(save) 
  {
    saveRDS(msb_v2,file)
  }
}

file=sprintf("%s/results/yoglen_noise_v2_step_function.rds",outputDir)
if(file.exists(file) & load)
{
  msn_v2=readRDS(file)
} else
{
  msn_v2 = ModelSelectionMI(mi,vars="var",xcol="tn2",models=models,Nfolds=5,Nrepeats=5,xdelta=c(.01,1,2,3,4,5,10),refModels = 1:length(models),mc.cores=mc.cores)
  if(save) 
  {
    saveRDS(msn_v2,file)
  }
}
```

```{r}
#agg0[,"model"]  = "Correct distribution"
#aggb_v1[,"model"] = "Distribution + 4 years"
#plotdf = rbind(agg0,aggb_v1)
plotdf = list(ms0$bestPr,msb_v1$bestPr)
plotdf[[1]][,"model"]  = "Correct distribution"
plotdf[[2]][,"model"] = "Distribution + 4 years"
for (i in 1:length(plotdf)) plotdf[[i]][,"t"] = plotdf[[i]][,"x"]
#plotdf = docall(rbind,plotdf)

print("normalized RMSE:")
for (i in 1:2) print(sqrt(mean((plotdf[[i]][,"y"] - 1*(plotdf[[i]][,"t"]>0))^2))/.1)

print("observed bias:")
print("pre-menopause:")
print(meansd(plotdf[[2]][plotdf[[2]][,"t"] < 0,"y"]-plotdf[[1]][plotdf[[1]][,"t"] < 0,"y"],sem=T))
print("post-menopause:")
print(meansd(plotdf[[2]][plotdf[[2]][,"t"] > 0,"y"]-plotdf[[1]][plotdf[[1]][,"t"] > 0,"y"],sem=T))

gtData= data.frame(t=seq(-25,25,by=.01),model="gt")
gtData[,"y"] = 1*(gtData[,"t"] > 0)
gtData[,"yse"] = 0

g = ggplot(plotdf[[1]],aes(x=t,y=y,ymin=y-yse,ymax=y+yse,colour=model,shape=model))+
  geom_line(data=gtData,size=1,colour="black")+
  #geom_ribbon(data=gtData,alpha=.25,colour=NA,fill="black")+
  geom_line(data=plotdf[[1]])+
  geom_point(data=plotdf[[2]])+
  geom_ribbon(data=plotdf[[1]],alpha=.25,colour=NA)+
  scale_x_continuous(limits=c(-5,5),breaks=-5:5)+
  scale_colour_brewer(palette="Accent")+
  scale_fill_brewer(palette="Accent")+
  labs(x="Time since menopause (years)",y="y",title="b)",colour="",shape="")+
  theme_minimal(base_size=26)+
  theme(axis.title.y=element_text(angle=0,vjust=.55))

g

#ggplot(agg2,aes(x=t,y=y,ymin=y-yse,ymax=y+yse))+
#  geom_pointrange()+
#  geom_line(data=noiseData,size=1,colour=cols[3])+
#  scale_x_continuous(limits=c(-5,5))+
#  theme_minimal()+
#  theme(axis.title.y=element_text(angle=0,vjust=.55))

save=gSaveDefault
if(save)
{
  library(cowplot)
  gleg = ggdraw(cowplot::get_legend(g))
  g = g + theme(legend.position="none")
  ggsave(sprintf("%s/results/step_function_sim_yoglen_bias_legend.pdf",outputDir),gleg,width=8,height=7)
  ggsave(sprintf("%s/results/step_function_sim_yoglen_bias.pdf",outputDir),g,width=8,height=7)
}
```

```{r}
#agg0[,"model"]  = "Correct distribution"
#aggn_v1[,"model"] = "Distribution + 4 years STD"
#plotdf = rbind(agg0,aggb_v1)
plotdf = list(ms0$bestPr,msn_v1$bestPr)
plotdf[[1]][,"model"]  = "Correct distribution"
plotdf[[2]][,"model"] = "Distribution + 4 years STD"
for (i in 1:length(plotdf)) plotdf[[i]][,"t"] = plotdf[[i]][,"x"]
#plotdf = docall(rbind,plotdf)

print("normalized RMSE:")
for (i in 1:2) print(sqrt(mean((plotdf[[i]][,"y"] - 1*(plotdf[[i]][,"t"]>0))^2))/.1)

print("observed bias:")
print("pre-menopause:")
print(meansd(plotdf[[2]][plotdf[[2]][,"t"] < 0,"y"]-plotdf[[1]][plotdf[[1]][,"t"] < 0,"y"],sem=T))
print("post-menopause:")
print(meansd(plotdf[[2]][plotdf[[2]][,"t"] > 0,"y"]-plotdf[[1]][plotdf[[1]][,"t"] > 0,"y"],sem=T))

gtData= data.frame(t=seq(-25,25,by=.01),model="gt")
gtData[,"y"] = 1*(gtData[,"t"] > 0)
gtData[,"yse"] = 0

g = ggplot(plotdf[[1]],aes(x=t,y=y,ymin=y-yse,ymax=y+yse,colour=model,shape=model))+
  geom_line(data=gtData,size=1,colour="black")+
  #geom_ribbon(data=gtData,alpha=.25,colour=NA,fill="black")+
  geom_line(data=plotdf[[1]])+
  geom_point(data=plotdf[[2]])+
  geom_ribbon(data=plotdf[[1]],alpha=.25,colour=NA)+
  scale_x_continuous(limits=c(-5,5),breaks=-5:5)+
  scale_colour_brewer(palette="Accent")+
  scale_fill_brewer(palette="Accent")+
  labs(x="Time since menopause (years)",y="y",title="c)",colour="",shape="")+
  theme_minimal(base_size=26)+
  theme(axis.title.y=element_text(angle=0,vjust=.55))

g

#ggplot(agg2,aes(x=t,y=y,ymin=y-yse,ymax=y+yse))+
#  geom_pointrange()+
#  geom_line(data=noiseData,size=1,colour=cols[3])+
#  scale_x_continuous(limits=c(-5,5))+
#  theme_minimal()+
#  theme(axis.title.y=element_text(angle=0,vjust=.55))

save=gSaveDefault
if(save)
{
  library(cowplot)
  gleg = ggdraw(cowplot::get_legend(g))
  g = g + theme(legend.position="none")
  ggsave(sprintf("%s/results/step_function_sim_yoglen_noise_legend.pdf",outputDir),gleg,width=8,height=7)
  ggsave(sprintf("%s/results/step_function_sim_yoglen_noise.pdf",outputDir),g,width=8,height=7)
}
```

```{r}
#agg0[,"model"]  = "Correct distribution"
#aggb_v1[,"model"] = "Distribution + 4 years"
#plotdf = rbind(agg0,aggb_v1)
plotdf = list(ms0$bestPr,msb_v2$bestPr)
plotdf[[1]][,"model"]  = "Correct distribution"
plotdf[[2]][,"model"] = "Distribution + 4 years"
for (i in 1:length(plotdf)) plotdf[[i]][,"t"] = plotdf[[i]][,"x"]
#plotdf = docall(rbind,plotdf)

gtData= data.frame(t=seq(-25,25,by=.01),model="gt")
gtData[,"y"] = 1*(gtData[,"t"] > 0)
gtData[,"yse"] = 0

print("normalized RMSE:")
for (i in 1:2) print(sqrt(mean((plotdf[[i]][,"y"] - 1*(plotdf[[i]][,"t"]>0))^2))/.1)
#print(sqrt(mean((plotdf[[2]][,"y"] - 1*(plotdf[[2]][,"t"]>0))^2))/sqrt(mean((plotdf[[1]][,"y"] - 1*(plotdf[[1]][,"t"]>0))^2)))


g = ggplot(plotdf[[1]],aes(x=t,y=y,ymin=y-yse,ymax=y+yse,colour=model,shape=model))+
  geom_line(data=gtData,size=1,colour="black")+
  geom_line(data=plotdf[[1]])+
  geom_point(data=plotdf[[2]])+
  geom_ribbon(data=plotdf[[1]],alpha=.25,colour=NA)+
  scale_x_continuous(limits=c(-5,5),breaks=-5:5)+
  scale_colour_brewer(palette="Accent")+
  scale_fill_brewer(palette="Accent")+
  labs(x="Time since menopause (years)",y="y",title="d)",colour="",shape="")+
  theme_minimal(base_size=26)+
  theme(axis.title.y=element_text(angle=0,vjust=.55))

g

#ggplot(agg2,aes(x=t,y=y,ymin=y-yse,ymax=y+yse))+
#  geom_pointrange()+
#  geom_line(data=noiseData,size=1,colour=cols[3])+
#  scale_x_continuous(limits=c(-5,5))+
#  theme_minimal()+
#  theme(axis.title.y=element_text(angle=0,vjust=.55))

save=gSaveDefault
if(save)
{
  library(cowplot)
  gleg = ggdraw(cowplot::get_legend(g))
  g = g + theme(legend.position="none")
  ggsave(sprintf("%s/results/step_function_sim_yoglen+v2_bias_legend.pdf",outputDir),gleg,width=8,height=7)
  ggsave(sprintf("%s/results/step_function_sim_yoglen_v2_bias.pdf",outputDir),g,width=8,height=7)
}
```

```{r}
#agg0[,"model"]  = "Correct distribution"
#aggn_v2[,"model"] = "Distribution + 4 years STD"
#plotdf = rbind(agg0,aggb_v1)
plotdf = list(ms0$bestPr,msn_v2$bestPr)
plotdf[[1]][,"model"]  = "Correct distribution"
plotdf[[2]][,"model"] = "Distribution + 4 years STD"
for (i in 1:length(plotdf)) plotdf[[i]][,"t"] = plotdf[[i]][,"x"]
#plotdf = docall(rbind,plotdf)


gtData= data.frame(t=seq(-25,25,by=.01),model="gt")
gtData[,"y"] = 1*(gtData[,"t"] > 0)
gtData[,"yse"] = 0

g = ggplot(plotdf[[1]],aes(x=t,y=y,ymin=y-yse,ymax=y+yse,colour=model,shape=model))+
  geom_line(data=gtData,size=1,colour="black")+
  #geom_ribbon(data=gtData,alpha=.25,colour=NA,fill="black")+
  geom_line(data=plotdf[[1]])+
  geom_point(data=plotdf[[2]])+
  geom_ribbon(data=plotdf[[1]],alpha=.25,colour=NA)+
  scale_x_continuous(limits=c(-5,5),breaks=-5:5)+
  scale_colour_brewer(palette="Accent")+
  scale_fill_brewer(palette="Accent")+
  labs(x="Time since menopause (years)",y="y",title="e)",colour="",shape="")+
  theme_minimal(base_size=26)+
  theme(axis.title.y=element_text(angle=0,vjust=.55))

g

#ggplot(agg2,aes(x=t,y=y,ymin=y-yse,ymax=y+yse))+
#  geom_pointrange()+
#  geom_line(data=noiseData,size=1,colour=cols[3])+
#  scale_x_continuous(limits=c(-5,5))+
#  theme_minimal()+
#  theme(axis.title.y=element_text(angle=0,vjust=.55))

save=gSaveDefault
if(save)
{
  library(cowplot)
  gleg = ggdraw(cowplot::get_legend(g))
  g = g + theme(legend.position="none")
  ggsave(sprintf("%s/results/step_function_sim_yoglen_v2_noise_legend.pdf",outputDir),gleg,width=8,height=7)
  ggsave(sprintf("%s/results/step_function_sim_yoglen_v2_noise.pdf",outputDir),g,width=8,height=7)
}
```


